using FluentMigrator;
using FluentMigrator.SqlServer;

namespace Dew.Migrations.DefaultDB;

[Migration(20240202_1210)]
public class DefaultDB_20240202_1210_InitialData : AutoReversingMigration
{
    public override void Up()
    {
        IfDatabase("PostgreSQL").Execute.Sql(@"
            ALTER TABLE public.""Users"" ALTER COLUMN ""UserId"" SET GENERATED BY DEFAULT;
            ALTER TABLE public.""Roles"" ALTER COLUMN ""RoleId"" SET GENERATED BY DEFAULT;
        ");

        Insert.IntoTable("Users").WithIdentityInsert().Row(new
        {
            UserId = 1,
            Username = "admin",
            DisplayName = "James Smith",
            Email = "moj.jahanbakhsh@gmail.com",
            Source = "site",
            PasswordHash = "Tbx1ar3apCdhYLcYXKqmO5klUr35ehupfPI0pAAsDlesD91YgTwFawmWURhtO7IzJNvtAJx67FYT05uVEtKYGw",
            PasswordSalt = "air_o",
            InsertDate = new DateTime(2024, 1, 1),
            UserImage = "UserImage/00000/00000001_vl5w3jzy763w2.jpg",
            InsertUserId = 1,
            IsActive = 1
        });

        Insert.IntoTable("Roles").WithIdentityInsert()
            .Row(new { RoleId = 1, RoleName = "Admin" })
            .Row(new { RoleId = 2, RoleName = "Support" })
            .Row(new { RoleId = 3, RoleName = "Develop" })
            .Row(new { RoleId = 4, RoleName = "Supervisor" })
            .Row(new { RoleId = 5, RoleName = "User" });

        Insert.IntoTable("RolePermissions")
            .Row(new { RoleId = 1, PermissionKey = "Dew:General" })
            .Row(new { RoleId = 1, PermissionKey = "Dew:Ticket:View" })
            .Row(new { RoleId = 1, PermissionKey = "Dew:Ticket:Create" })
            .Row(new { RoleId = 1, PermissionKey = "Dew:Ticket:Update" })
            .Row(new { RoleId = 1, PermissionKey = "Dew:Ticket:Admin" })
            .Row(new { RoleId = 1, PermissionKey = "Workflow:View" })
            .Row(new { RoleId = 1, PermissionKey = "Workflow:Modify" })
            .Row(new { RoleId = 1, PermissionKey = "Administration:Security" })
            .Row(new { RoleId = 1, PermissionKey = "Administration:Translation" })

            .Row(new { RoleId = 2, PermissionKey = "Dew:Ticket:Update" })
            .Row(new { RoleId = 2, PermissionKey = "Workflow:View" })
            .Row(new { RoleId = 3, PermissionKey = "Dew:Ticket:Update" })
            .Row(new { RoleId = 3, PermissionKey = "Workflow:View" })
            .Row(new { RoleId = 4, PermissionKey = "Dew:Ticket:Update" })
            .Row(new { RoleId = 4, PermissionKey = "Workflow:View" })
            
            .Row(new { RoleId = 5, PermissionKey = "Dew:Ticket:Create" })
            .Row(new { RoleId = 5, PermissionKey = "Workflow:View" });

        IfDatabase("PostgreSQL").Execute.Sql("""
            ALTER TABLE public."Users" ALTER COLUMN "UserId" SET GENERATED ALWAYS;
            ALTER TABLE public."Roles" ALTER COLUMN "RoleId" SET GENERATED ALWAYS;
            SELECT setval('"Users_UserId_seq"', (SELECT MAX("UserId") FROM "Users"), true);
            SELECT setval('"Roles_RoleId_seq"', (SELECT MAX("RoleId") FROM "Roles"), true);
        """);
    }
}